"use client";

import React, { useState } from "react";
import { useApp } from "@/components/providers/Providers";
import { useStore } from "@/lib/store";
import {
  FileText,
  Download,
  Sparkles,
  Printer,
  Calendar,
  Layers,
  CheckCircle2,
  Share2,
} from "lucide-react";

export default function ReportsPage() {
  const { kpis } = useStore();
  const { triggerAiPrompt } = useApp();
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
    }, 800);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="card p-5 border border-gt-border flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1 rounded bg-gt-green/20 text-gt-green">
              <FileText className="w-4 h-4" />
            </span>
            <span className="text-xs font-mono text-gt-green uppercase tracking-wider font-bold">
              Autonomous Dossier Synthesis
            </span>
            <span className="badge badge-success text-[10px] font-mono">VERIFIABLE CITATIONS</span>
          </div>
          <h1 className="text-xl font-bold text-white font-sans">
            Executive Intelligence Reports & Board Dossiers
          </h1>
          <p className="text-xs text-gt-muted mt-0.5">
            Automated compilation of executive summaries, critical KPIs, detected anomalies, predictive trends, and strategic action plans.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleGenerateReport}
            disabled={isGenerating}
            className="btn btn-primary text-xs py-2 px-3.5 flex items-center gap-2"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>{isGenerating ? "Synthesizing Dossier..." : "Generate AI Executive Report"}</span>
          </button>
        </div>
      </div>

      {/* Generated Report Preview Card */}
      <div className="card p-6 border border-gt-border space-y-6 bg-gt-surface/80">
        {/* Report Top Meta */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-gt-border">
          <div>
            <span className="text-[10px] font-mono text-gt-green uppercase tracking-wider">
              CONFIDENTIAL • ENTERPRISE BOARD DOSSIER
            </span>
            <h2 className="text-lg font-bold text-white font-sans mt-0.5">
              GreenTrail Operations & Revenue Performance — Q3 Executive Brief
            </h2>
            <div className="text-xs text-gt-muted font-mono mt-1">
              Generated by Green AI • Telemetry Window: Last 30 Days • Data Sources: 12 Connected Systems
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="btn btn-secondary text-xs py-1.5 px-3 flex items-center gap-1.5"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={() => alert("Dossier exported to JSON schema")}
              className="btn btn-secondary text-xs py-1.5 px-3 flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export JSON</span>
            </button>
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="space-y-2">
          <h3 className="text-xs font-mono font-bold text-gt-green uppercase tracking-wider">
            1. Executive Summary
          </h3>
          <p className="text-xs text-gt-text-1 leading-relaxed">
            GreenTrail Technologies demonstrated resilient trajectory during the current reporting cycle, realizing gross revenue of <strong>₹{kpis.revenueLakhs.toFixed(2)} Lakhs</strong> representing a <strong>+14.2%</strong> lift relative to baseline expectations. Growth was primarily catalyzed by elevated weekend booking frequency in Tier-1 logistics corridors, coupled with high customer acquisition efficiency on Instagram and direct WhatsApp automated booking channels.
          </p>
        </div>

        {/* Section 2: Key Metrics Matrix */}
        <div className="space-y-2">
          <h3 className="text-xs font-mono font-bold text-gt-green uppercase tracking-wider">
            2. Core Business Metrics (Verified)
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="p-3 rounded bg-gt-card border border-gt-border">
              <div className="text-[10px] text-gt-muted">Gross Revenue</div>
              <div className="text-sm font-bold text-white font-mono mt-0.5">₹{kpis.revenueLakhs.toFixed(2)}L</div>
              <div className="text-[10px] text-gt-green font-mono">+14.2% MoM</div>
            </div>
            <div className="p-3 rounded bg-gt-card border border-gt-border">
              <div className="text-[10px] text-gt-muted">Active Users</div>
              <div className="text-sm font-bold text-white font-mono mt-0.5">{kpis.activeUsers.toLocaleString()}</div>
              <div className="text-[10px] text-gt-green font-mono">+8.6% engagement</div>
            </div>
            <div className="p-3 rounded bg-gt-card border border-gt-border">
              <div className="text-[10px] text-gt-muted">Completed Bookings</div>
              <div className="text-sm font-bold text-white font-mono mt-0.5">{kpis.bookings.toLocaleString()}</div>
              <div className="text-[10px] text-gt-green font-mono">98.9% fulfillment</div>
            </div>
            <div className="p-3 rounded bg-gt-card border border-gt-border">
              <div className="text-[10px] text-gt-muted">Blended CAC</div>
              <div className="text-sm font-bold text-white font-mono mt-0.5">₹395</div>
              <div className="text-[10px] text-gt-green font-mono">Top decile efficiency</div>
            </div>
          </div>
        </div>

        {/* Section 3: Anomalies & Detected Drift */}
        <div className="space-y-2">
          <h3 className="text-xs font-mono font-bold text-gt-green uppercase tracking-wider">
            3. Anomalies & Operational Risk Factors
          </h3>
          <div className="p-3 rounded bg-gt-card border border-gt-border text-xs text-gt-text-2 space-y-1.5">
            <div>• <strong>Search Ad CPC Surge:</strong> Google Ads cost-per-click experienced a localized 12% rise due to competitor bidding across Western India.</div>
            <div>• <strong>Single Account Churn Watch:</strong> Account #10393 (Zenith Logistics) logged declining activity over a 14-day window. Retention intervention initiated.</div>
          </div>
        </div>

        {/* Section 4: Strategic Recommendations */}
        <div className="space-y-2">
          <h3 className="text-xs font-mono font-bold text-gt-green uppercase tracking-wider">
            4. Strategic Action Plan & Recommendations
          </h3>
          <div className="p-3 rounded bg-gt-card border border-gt-border text-xs text-gt-text-2 space-y-1.5">
            <div>1. Reallocate 20% of Google Search ad spend into high-performing WhatsApp direct booking pilot.</div>
            <div>2. Schedule executive check-in with Account #10393 to present preferred route discount structure.</div>
            <div>3. Expand connector throughput buffer to support upcoming Diwali peak volume surges.</div>
          </div>
        </div>
      </div>
    </div>
  );
}
